name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd HolaMundo  # Cambiar al directorio donde está el package.json
        npm install

    - name: Run tests
      run: |
        cd HolaMundo  # Asegurarse de estar en el directorio correcto
        npm test
